[tool.poetry]
name = "typegql"
version = "1.1.0"
description = "A Python GraphQL library that makes use of type hinting and concurrency support with the new async/await syntax."
authors = ["Ciprian Tarta <ciprian@cipriantarta.ro>"]
license = "MIT"

readme = 'README.rst'  # Markdown files are supported

repository = "https://github.com/cipriantarta/typegql"
homepage = "https://github.com/cipriantarta/typegql"

keywords = ['graphql', 'python', 'asyncio', 'generics', 'typing']

[tool.poetry.dependencies]
python = "^3.7"
uvloop = "^0.11.2"
graphql-core-next = "^1.0"
aiohttp = {version = "^3.4", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^3.9"
pytest-asyncio = "^0.9.0"
pytest-flake8 = "^1.0"
sanic = "^0.8.3"

[tool.poetry.extras]
client = ["aiohttp", "cchardet"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
